// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_f1omKbn5tpdOh89WjqPQOUFO2Pv-yss',
    appId: '1:19513178393:web:4d03a263ef576a70ac6d88',
    messagingSenderId: '19513178393',
    projectId: 'sudtogethor',
    authDomain: 'sudtogethor.firebaseapp.com',
    storageBucket: 'sudtogethor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-gHGlGN81Vvd3kSvUlLZYR2W4IGprgM',
    appId: '1:19513178393:android:21565b852b3753bcac6d88',
    messagingSenderId: '19513178393',
    projectId: 'sudtogethor',
    storageBucket: 'sudtogethor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMmTbpiZXDWHhmhhVGg6ZDMcTtNXxsjg',
    appId: '1:19513178393:ios:ec3294ca3f4b8beaac6d88',
    messagingSenderId: '19513178393',
    projectId: 'sudtogethor',
    storageBucket: 'sudtogethor.appspot.com',
    iosBundleId: 'com.ragabaat.sdtogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMmTbpiZXDWHhmhhVGg6ZDMcTtNXxsjg',
    appId: '1:19513178393:ios:ed5b8c701a1b0f5bac6d88',
    messagingSenderId: '19513178393',
    projectId: 'sudtogethor',
    storageBucket: 'sudtogethor.appspot.com',
    iosBundleId: 'com.ragabaat.sdtogether.RunnerTests',
  );
}
